### ISSUE TITLE
Bandainamco scraper is inactive on scraper.peviitor.ro

### ISSUE THREAD

**Issue by SimonaNemtanu** [peviitor-ro/scrapers_Larisa_M16#10]
ENVIRONMENT: Windows, Mozilla Firefox
URL: https://scrapers.peviitor.ro/

STEPS TO REPRODUCE:

Open URL.
Type Bandainamco in the search bar.
Click on Bandainamco
Run Scraper function.

Expected results: We should have a result with company jobs

Actual results: Scraper is not loading . Status inactive
![image](https://github.com/peviitor-ro/Scrapers_start_with_digi/assets/140648185/cc473405-3207-424f-949e-03d49e9f8494)

**Comment by LarisaM16** [comment]
company page is inactive.
