### ISSUE TITLE
Bitpanda scraper is inactive on scraper.peviitor.ro

### ISSUE THREAD

**Issue by SimonaNemtanu** [peviitor-ro/scrapers_Larisa_M16#12]
ENVIRONMENT: Windows, Mozilla Firefox
URL: https://scrapers.peviitor.ro/
Device: Laptop
OS: Windows 10 Pro

STEPS TO REPRODUCE:

Open URL.
Type Bitpanda in the search bar.
Click on Bitpanda
Run Scraper function.

Expected results: We should have a result with company jobs

Actual results: Scraper is not loading . Status inactive

![image](https://github.com/peviitor-ro/scrapers_Larisa_M16/assets/140648185/2bb23934-01fb-4641-b155-97327e7a2ad6)

**Comment by LarisaM16** [comment]
Now looks ok. please retest. 
![Screenshot_31](https://github.com/peviitor-ro/scrapers_Larisa_M16/assets/124587607/4e9b5548-e6e8-48d0-8af4-5c68f69168bd)

**Comment by SimonaNemtanu** [comment]
Same 

![image](https://github.com/peviitor-ro/scrapers_Larisa_M16/assets/140648185/cc89c8d7-584d-403d-b18e-e881df24ccf1)

**Comment by LarisaM16** [comment]
@lalalaurentiu please help. status is inactive

**Comment by LarisaM16** [comment]
@SimonaNemtanu 
![image](https://github.com/peviitor-ro/scrapers_Larisa_M16/assets/124587607/5ad43c22-3544-482d-9849-2227fca44989)
please retest

**Comment by SimonaNemtanu** [comment]
Closed #12 as completed 
![image](https://github.com/peviitor-ro/scrapers_Larisa_M16/assets/140648185/3322fcec-c8ed-4eb2-ab3b-59bc30ce5f8d)
