### ISSUE TITLE
Bunge scraper is inactive on scraper.peviitor.ro

### ISSUE THREAD

**Issue by SimonaNemtanu** [peviitor-ro/scrapers_Larisa_M16#13]
ENVIRONMENT: Windows, Mozilla Firefox
URL: https://scrapers.peviitor.ro/

STEPS TO REPRODUCE:

Open URL.
Type Bunge in the search bar.
Click on Bunge
Run Scraper function.

Expected results: We should have a result with company jobs

Actual results: Scraper is not loading . Status inactive
![image](https://github.com/peviitor-ro/scrapers_Larisa_M16/assets/140648185/4f2bcafb-18bf-41e2-9ab6-99bb753b6f4b)

**Comment by LarisaM16** [comment]
Now looks ok. please retest. 
![Screenshot_33](https://github.com/peviitor-ro/scrapers_Larisa_M16/assets/124587607/8c3c050d-2739-40f6-b043-b8f911fb956d)

**Comment by SimonaNemtanu** [comment]
Same 
![image](https://github.com/peviitor-ro/scrapers_Larisa_M16/assets/140648185/a55a1e00-4e1b-4af9-80b4-bc100ea55c1a)

**Comment by LarisaM16** [comment]
@lalalaurentiu  
![image](https://github.com/peviitor-ro/scrapers_Larisa_M16/assets/124587607/3dabcbad-afbb-4821-949f-455caaedd224)

**Comment by LarisaM16** [comment]
@SimonaNemtanu 
![image](https://github.com/peviitor-ro/scrapers_Larisa_M16/assets/124587607/e702c209-41ee-43d0-a6ff-a20887692b76)
please retest

**Comment by SimonaNemtanu** [comment]
Closed #13 as completed 
![image](https://github.com/peviitor-ro/scrapers_Larisa_M16/assets/140648185/f1ce143c-370a-42c2-860d-97e0af08ca25)
