### ISSUE TITLE
CanamGroup scraper is inactive on scraper.peviitor.ro

### ISSUE THREAD

**Issue by SimonaNemtanu** [peviitor-ro/scrapers_Larisa_M16#16]
ENVIRONMENT: Windows, Mozilla Firefox
URL: https://scrapers.peviitor.ro/
Device: Laptop

STEPS TO REPRODUCE:

Open URL.
Type CanamGroup in the search bar.
Click on CanamGroup
Run Scraper function.

Expected results: We should have a result with company jobs

Actual results: Scraper is not loading . Status inactive
![image](https://github.com/peviitor-ro/scrapers_Larisa_M16/assets/140648185/43885d7a-3008-433f-8d91-bc5f14a19465)

**Comment by LarisaM16** [comment]
![image](https://github.com/peviitor-ro/scrapers_Larisa_M16/assets/124587607/c8b21747-3e69-44e9-8ad2-c5ac6f878ccf)
please retest.

**Comment by LarisaM16** [comment]
@lalalaurentiu

**Comment by LarisaM16** [comment]
![image](https://github.com/peviitor-ro/scrapers_Larisa_M16/assets/124587607/064bc70d-82fa-47d9-b1f1-4be527a3304f)
please retest @SimonaNemtanu

**Comment by SimonaNemtanu** [comment]
Closed #16 as completed
![image](https://github.com/peviitor-ro/scrapers_Larisa_M16/assets/140648185/2d533bed-3256-431f-9fc2-e698f51efc69)
