### ISSUE TITLE
Job City Field is empty in the API Response for c4media

### ISSUE THREAD

**Issue by RaresCode** [peviitor-ro/scrapers_Larisa_M16#19]
ENVIRONMENT: production
URL: https://peviitor.ro
Browser: Brave
Version: 120
Device: Desktop
OS: Windows 10

STEPS TO REPRODUCE:
 1. Make an API request for the c4media jobs on peviitor API
 2. Pay attention to the missing job cities from the APIresponse

EXPECTED RESULTS:
The job city is displayed for every job in the job city field within the API response for the c4media

ACTUAL RESULTS:
The job city field is empty for every job within the API response

Attachments:
![image](https://github.com/peviitor-ro/scrapers_Larisa_M16/assets/91252395/e34ebdee-3bcf-48a5-a02e-eddf054610ca)

**Comment by LarisaM16** [comment]
@RaresCode hello! Please retest

**Comment by RaresCode** [comment]
Retested, it seems fine
