### ISSUE TITLE
Centric - Jobs number discrepancy

### ISSUE THREAD

**Issue by SimonaNemtanu** [peviitor-ro/scrapers_Larisa_M16#22]
ENVIRONMENT: Windows, Mozilla Firefox
URL: https://scrapers.peviitor.ro/

STEPS TO REPRODUCE:

Open URL
Type Centric in the search bar
Click on Centric
Run Scraper
Click on See Jobs button

Expected results
The number of jobs displayed on the site matches the number of jobs after clicking on the See jobs button 

Actual results
2 jobs are displayed on site, 0 jobs are displayed after clicking the See jobs button 

![image](https://github.com/peviitor-ro/scrapers_Larisa_M16/assets/140648185/1c8969fd-f541-4207-b58b-71cf46a5a233)

![image](https://github.com/peviitor-ro/scrapers_Larisa_M16/assets/140648185/1f34ba2b-e8fc-4abb-b4f3-a027c5f27c2c)

**Comment by LarisaM16** [comment]
![image](https://github.com/peviitor-ro/scrapers_Larisa_M16/assets/124587607/568fc09c-11f8-4756-b2bb-4384de60fa65)
retest!

**Comment by SimonaNemtanu** [comment]
Closed #22 as completed
