### ISSUE TITLE
CGS Romania - Logo is missing on https://firme.peviitor.ro

### ISSUE THREAD

**Issue by SimonaNemtanu** [peviitor-ro/scrapers_Larisa_M16#24]
ENVIRONMENT: Windows, Mozilla Firefox
URL: https://firme.peviitor.ro/

STEPS TO REPRODUCE:
Open URL
Type CGS Romania in the search bar
See the logo

Expected results
The CGS Romania company logo is displayed.

Actual results
The message "The logo is not found" is displayed
![image](https://github.com/peviitor-ro/scrapers_Larisa_M16/assets/140648185/2c36cfe4-6624-410e-b6eb-e2c65fb272d2)

**Comment by LarisaM16** [comment]
![image](https://github.com/peviitor-ro/scrapers_Larisa_M16/assets/124587607/d6fbb11a-fc23-4bc5-9d7f-86a2be2b0930)
Please retest
