### ISSUE TITLE
Corteva - Two logos displayed for the same company

### ISSUE THREAD

**Issue by SimonaNemtanu** [peviitor-ro/scrapers_Larisa_M16#29]
ENVIRONMENT: Windows, Mozilla Firefox
URL: https://firme.peviitor.ro/
Device: Laptop
OS: Windows 10 Pro

STEPS TO REPRODUCE:

    Open URL in browser
    Type "Corteva " in the search bar

EXPECTED RESULTS:
The logo company must be displayed only once.

ACTUAL RESULTS:
There are displayed two companies with the same name.

![image](https://github.com/peviitor-ro/scrapers_Larisa_M16/assets/140648185/a03bcca9-8678-44a2-9cd4-109e79a3a8a4)

**Comment by LarisaM16** [comment]
Done! 
![image](https://github.com/peviitor-ro/scrapers_Larisa_M16/assets/124587607/3adf81f0-0900-4348-be96-e7e2e6956a3e)

**Comment by SimonaNemtanu** [comment]
Closed #29 as completed
