### ISSUE TITLE
Monefy - Two logos displayed for the same company

### ISSUE THREAD

**Issue by SimonaNemtanu** [peviitor-ro/scrapers_Larisa_M16#40]
ENVIRONMENT: Windows, Mozilla Firefox
URL: https://firme.peviitor.ro/
Device: Laptop
OS: Windows 10 Pro

STEPS TO REPRODUCE:

Open URL in browser
Type "Monefy " in the search bar

EXPECTED RESULTS:
The logo company must be displayed only once.

ACTUAL RESULTS:
There are displayed two companies with the same name.
![image](https://github.com/peviitor-ro/scrapers_Larisa_M16/assets/140648185/7641b701-d385-4ffa-b91a-54e29f71c23d)

**Comment by LarisaM16** [comment]
please retest 
![image](https://github.com/peviitor-ro/scrapers_Larisa_M16/assets/124587607/5577152f-182a-4f25-9497-7fc5f45448c1)
