### ISSUE TITLE
Yopeso - Two logos displayed for the same company

### ISSUE THREAD

**Issue by SimonaNemtanu** [peviitor-ro/scrapers_Larisa_M16#46]
ENVIRONMENT: Windows, Mozilla Firefox
URL: https://firme.peviitor.ro/
Device: Laptop
OS: Windows 10 Pro

STEPS TO REPRODUCE:

Open URL in browser
Type "Yopeso " in the search bar

EXPECTED RESULTS:
The logo company must be displayed only once.

ACTUAL RESULTS:
There are displayed two logos with the same name.

![image](https://github.com/peviitor-ro/scrapers_Larisa_M16/assets/140648185/380b3a2d-4eca-451b-a6a1-16c4e7736944)

**Comment by LarisaM16** [comment]
please retest 
![image](https://github.com/peviitor-ro/scrapers_Larisa_M16/assets/124587607/809f7a57-80e2-450b-9c80-cf7209440d59)

**Comment by SimonaNemtanu** [comment]
Closed #46 as completed
