### ISSUE TITLE
Azets scraper is inactive on scraper.peviitor.ro

### ISSUE THREAD

**Issue by SimonaNemtanu** [peviitor-ro/scrapers_Larisa_M16#9]
ENVIRONMENT: Windows, Mozilla Firefox
URL: https://scrapers.peviitor.ro/
Device: Laptop
OS: Windows 10 Pro

STEPS TO REPRODUCE:

Open URL.
Type Azets in the search bar.
Click on Azets
Run Scraper function.

Expected results: We should have a result with company jobs

Actual results: Scraper is not loading . Status inactive
![image](https://github.com/peviitor-ro/Scrapers_start_with_digi/assets/140648185/f3297b5d-17be-4e5b-87aa-517f1ba7eef9)

**Comment by LarisaM16** [comment]
Now looks ok. please retest.
![Screenshot_32](https://github.com/peviitor-ro/scrapers_Larisa_M16/assets/124587607/4a4418e4-26d2-4dd6-bfaf-48505d40b228)

**Comment by SimonaNemtanu** [comment]
Same 

![image](https://github.com/peviitor-ro/scrapers_Larisa_M16/assets/140648185/e680f2d1-a9e4-44cf-ba04-d326ff631433)

**Comment by LarisaM16** [comment]
@lalalaurentiu

**Comment by SimonaNemtanu** [comment]
Closed #9 as completed 
![image](https://github.com/peviitor-ro/scrapers_Larisa_M16/assets/140648185/ba0b991d-e25d-4eb1-8487-f2a0cba006cd)
